#!/bin/sh
# by Dominik Stanisław Suchora <suchora.dominik7@gmail.com>
# License: GNU GPLv3

PAGE=1
SEARCH=""
DOMAIN="https://www.alldatasheet.com"
DELIM="\t"

user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36"
alias ucurl="curl -L -g -s --user-agent \"$user_agent\" -H 'Accept-Encoding: gzip, deflate, br' --compressed"

C_MAN="39"
C_DESC="32"
C_SIZE="33"
C_NAME="34"
COLOR=1

while [ $# -gt 0 ]
do
  case "$1" in
    -h|--help)
        NAME="$(basename "$0")"
        printf "%s [OPTION]... [PATTERN]\nSearch for PATTERN in alldatasheet.\nExample: %s -s num -p 2 'lm317'\n\n" "$NAME" "$NAME"
        printf "Options:\n  -d,  --domain DOMAIN\t\tset domain to DOMAIN\n"
        printf "  -D,  --delimiter DELIM\tset delimiter to DELIM\n"
        printf "  -c,  --color\t\t\tcolor output\n"
        printf "  -C,  --no-color\t\tdisable coloring of output\n"
        printf "  -p,  --page NUM\t\tshow page at NUM\n"
        printf "  -h,  --help\t\t\tshow help\n"
        printf "\nUrl will be printed into stdout.\n"
        exit 0;;
    -d|--domain)
        DOMAIN="$2"
        shift 2;;
    -p|--page)
        PAGE="$2"
        shift 2;;
    -c|--color)
        COLOR=1
        shift;;
    -C|--no-color)
        COLOR=0
        shift;;
    -D|--delimiter)
        DELIM="$2"
        shift 2;;
    *)
      SEARCH="$1"
      shift;;
  esac
done

SEARCHP=$(echo "$SEARCH" | tr -d ' [:punct:]' | tr '[:lower:]' '[:upper:]')

t1=$(mktemp)
t_size=$(mktemp)
t_desc=$(mktemp)
t_name=$(mktemp)
t_link=$(mktemp)
t_man=$(mktemp)
trap 'rm "$t1" "$t_size" "$t_name" "$t_link" "$t_desc" "$t_man"' EXIT

LINK="$DOMAIN/view_datasheet.jsp?sSearchword=$SEARCHP&sPage=$PAGE&sField=0"
ucurl "$LINK" > "$t1"
reliq 'a +target="_blank" href=a>"/datasheet-pdf/pdf/" i@"<b>" | "https:%(href)v\n" / sed "s,/pdf/,/download/,"' "$t1" > "$t_link"
reliq 'a +target="_blank" href=a>"/datasheet-pdf/pdf/" | "https:%(href)v\n"; b | "%i\n"' "$t1" > "$t_name"
reliq 'img +class="abclogoyo" | "%(alt)v\n"' "$t1" > "$t_man"
reliq 'span +class="mobileblock" | "%i\n"' "$t1" > "$t_size"
grep -E '^<td>(<font.*</font>(&nbsp;){3}|(&nbsp;){3})' "$t1" | sed '/<font /s/.*;/\[old\] /; s/.*;//' > "$t_desc"

color_lines() {
    sed "s/^/\x1b[$1m/; s/$/\x1b[0m/" "$2" > "$3"
    cp "$3" "$2"
}

if [ "$COLOR" -eq 1 ]
then
    color_lines "$C_SIZE" "$t_size" "$t1"
    color_lines "$C_NAME" "$t_name" "$t1"
    color_lines "$C_MAN" "$t_man" "$t1"
    color_lines "$C_DESC" "$t_desc" "$t1"
fi

paste -d "$DELIM" "$t_name" "$t_size" "$t_desc" "$t_man" | nl
printf 'num> '
read -r NUMBER
[ "$NUMBER" -gt 0 ] && ucurl -g -s -L "$(sed "${NUMBER}q;d" "$t_link")" | reliq 'a +target="_blank" +href=e>"/datasheet.pdf" | "'"$DOMAIN"'%(href)v\n"' | tee /dev/stderr | tr -d '\n' | xclip -sel clip
